#!/bin/sh

GUILD_BINARY=${GUILD_BINARY:-guild}
GUILE_LOAD_PATH=$PWD/scheme
export GUILE_LOAD_PATH
rc=0

for dir in scheme/*/*/*/*/*/ scheme/*/*/*/*/ \
           scheme/*/*/*/ scheme/*/*/ scheme/*/ scheme/; do
    [ ! -d "$dir" ] && continue
    [ "$dir" = "scheme/test/" ] && continue
    printf 'Entering directory `%s'\''...\n' "$dir"
    (irc=0; cd "$dir" && for input in *.scm; do
                      [ ! -f "$input" ] && continue
                      output="${input%.*}.go"
                      [ -e "$output" ] && [ "$output" -nt "$input" ] && continue
                      echo ">>> $input"
            "$GUILD_BINARY" compile -Wunsupported-warning \
                                    -Wunused-variable \
                                    -Wunused-toplevel \
                                    -Wunbound-variable \
                                    -Warity-mismatch \
                                    -Wduplicate-case-datum \
                                    -Wbad-case-datum \
                                    -Wformat \
                                    -o "$output" "$input" || irc=1
                  done; exit "$irc"; ) || rc=1
done

exit $rc
